# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 584)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.name = QtWidgets.QLineEdit(Dialog)
        self.name.setObjectName("name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.deg = QtWidgets.QLineEdit(Dialog)
        self.deg.setObjectName("deg")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.deg)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.ground = QtWidgets.QComboBox(Dialog)
        self.ground.setObjectName("ground")
        self.ground.addItem("")
        self.ground.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ground)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.descrip = QtWidgets.QLineEdit(Dialog)
        self.descrip.setObjectName("descrip")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.descrip)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.price = QtWidgets.QSpinBox(Dialog)
        self.price.setMaximum(10000)
        self.price.setObjectName("price")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.price)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.volume = QtWidgets.QSpinBox(Dialog)
        self.volume.setMaximum(10000)
        self.volume.setObjectName("volume")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.volume)
        self.verticalLayout.addLayout(self.formLayout)
        self.add = QtWidgets.QPushButton(Dialog)
        self.add.setObjectName("add")
        self.verticalLayout.addWidget(self.add)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.deg_2 = QtWidgets.QLineEdit(Dialog)
        self.deg_2.setObjectName("deg_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.deg_2)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.ground_2 = QtWidgets.QComboBox(Dialog)
        self.ground_2.setObjectName("ground_2")
        self.ground_2.addItem("")
        self.ground_2.addItem("")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ground_2)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.descrip_2 = QtWidgets.QLineEdit(Dialog)
        self.descrip_2.setObjectName("descrip_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.descrip_2)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.price_2 = QtWidgets.QSpinBox(Dialog)
        self.price_2.setMaximum(10000)
        self.price_2.setObjectName("price_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.price_2)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.volume_2 = QtWidgets.QSpinBox(Dialog)
        self.volume_2.setMaximum(10000)
        self.volume_2.setObjectName("volume_2")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.volume_2)
        self.name_2 = QtWidgets.QComboBox(Dialog)
        self.name_2.setObjectName("name_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_2)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.change = QtWidgets.QPushButton(Dialog)
        self.change.setObjectName("change")
        self.verticalLayout.addWidget(self.change)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Название"))
        self.label_2.setText(_translate("Dialog", "Степень обжарки"))
        self.label_3.setText(_translate("Dialog", "Молотый/в зернах"))
        self.ground.setItemText(0, _translate("Dialog", "Молотый"))
        self.ground.setItemText(1, _translate("Dialog", "В зернах"))
        self.label_4.setText(_translate("Dialog", "Описание вкуса"))
        self.label_5.setText(_translate("Dialog", "Цена"))
        self.label_6.setText(_translate("Dialog", "Объём упаковки (г)"))
        self.add.setText(_translate("Dialog", "Добавить"))
        self.label_7.setText(_translate("Dialog", "Название"))
        self.label_8.setText(_translate("Dialog", "Степень обжарки"))
        self.label_9.setText(_translate("Dialog", "Молотый/в зернах"))
        self.ground_2.setItemText(0, _translate("Dialog", "Молотый"))
        self.ground_2.setItemText(1, _translate("Dialog", "В зернах"))
        self.label_10.setText(_translate("Dialog", "Описание вкуса"))
        self.label_11.setText(_translate("Dialog", "Цена"))
        self.label_12.setText(_translate("Dialog", "Объём упаковки (г)"))
        self.change.setText(_translate("Dialog", "Изменить"))
